# Excavator (machine 4): swing-drive motor and gearbox — sensor vs camera

| | Sensor | Camera |
|---|---|---|
| Data | CORA vibration (Vx, 3 kHz) | CORA infrared camera |
| Classes | healthy, bearing defect, unbalance, misalignment | same four |
| Tested on | 16 runs, one speed held out at a time | the same 16 runs |
| Code | `Models/excavator.py csv` | `Models/excavator.py cnn-pretrained` |

Same CORA laboratory motor/gearbox rig as the Belt Conveyor, but a **different task**: drive-train faults (bearing defect, unbalance, misalignment) instead of gear wear. Lab data, not an excavator; it classifies the present condition, not when to repair.

All of this machine's experiment code is in its `Models/` file; shared notebook set-up is in `notebook_helpers.py`. Run the cells from top to bottom with the **Capstone (.venv)** kernel.

In [1]:
from notebook_helpers import *

LOCAL = setup([
    ("Sensor: CORA vibration (16 runs)", "Raw_Data/cora_vibration", "*_Vx.csv", 16),
    ("Camera: CORA infrared, faults", "Raw_Data/cora_drive_faults", "*.mat", 12),
    ("Camera: CORA infrared, healthy", "Raw_Data/cora_gear_wear", "H_*.mat", 4),
])

                 environment
git commit           cf5f533
python                3.11.9
kernel         project .venv
numpy                  2.4.6
scipy                 1.17.1
pandas                 2.3.3
scikit-learn           1.9.1
opencv-python      4.14.0.94
matplotlib            3.11.2

,location,files,MB,local
data,,,,
Sensor: CORA vibration (16 runs),Raw_Data/cora_vibration,28/16,3078.1,True
"Camera: CORA infrared, faults",Raw_Data/cora_drive_faults,12/12,269.6,True
"Camera: CORA infrared, healthy",Raw_Data/cora_gear_wear,4/4,118.2,True

All data is local: running fully offline.

## 1. Sensor: vibration (CSV)
Each run's vibration becomes 1-second windows measured in **shaft orders** (multiples of the shaft speed): unbalance shows at 1x, misalignment at 2x, bearing defects at higher orders and spikes. The features go into a CSV table; the model and feature set are chosen on validation speeds inside the training data, then tested once on the held-out speed.

In [2]:
if all(LOCAL.values()):
    run_script("Models/excavator.py", "csv", tail=2)                    # main: unseen speed
    run_script("Models/excavator.py", "csv", "--split", "time", tail=1)  # secondary: time split
csv_result, time_result = load("excavator_csv_4class.json"), load("excavator_csv_4class_timesplit.json")
show({"MAIN (unseen speed) | Sensor: validation-selected": csv_result["validation_selected"]["score"],
      **{f"MAIN (unseen speed) | Sensor: {k}": v for k, v in csv_result["models"].items()},
      **{f"TIME SPLIT | Sensor: {k}": v for k, v in time_result["models"].items()}})

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

[Models/excavator.py csv]
  Validation-selected model: accuracy 0.188  macro F1 0.129  (choices: ['vibration (per-speed normalised) / Extra trees', 'vibration (per-speed normalised) / Random forest', 'vibration / Logistic regression', 'vibration / Gradient boosting'])
  Saved Processed_Data\excavator_sensor_features_4class.csv, Results\excavator\excavator_csv_4class.json and Figures\excavator\excavator_csv_4class.png

[Models/excavator.py csv --split time]
  Saved Results\excavator\excavator_csv_4class_timesplit.json and Figures\excavator\excavator_csv_4class_timesplit.png

,accuracy,balanced_accuracy,macro_precision,macro_recall,macro_f1
MAIN (unseen speed) | Sensor: validation-selected,0.188,0.188,0.098,0.188,0.129
MAIN (unseen speed) | Sensor: Majority class (control),0.250,0.250,0.062,0.250,0.100
MAIN (unseen speed) | Sensor: Logistic regression,0.188,0.188,0.075,0.188,0.107
MAIN (unseen speed) | Sensor: Random forest,0.250,0.250,0.184,0.250,0.209
TIME SPLIT | Sensor: Majority class (control),0.250,0.250,0.062,0.250,0.100
TIME SPLIT | Sensor: Logistic regression,0.812,0.812,0.825,0.812,0.811
TIME SPLIT | Sensor: Random forest,0.938,0.938,0.950,0.938,0.936

![CSV sensor model](../Figures/excavator/excavator_csv_4class.png) ![Time split](../Figures/excavator/excavator_csv_4class_timesplit.png)

**Two tests, clearly separated.** *Main (unseen speed):* each whole speed is held out, so the model must recognise a fault at a speed it never trained on; CORA has only one run per fault per speed, and every model stays near chance. *Time split (secondary, easier):* the first 60% of every 45-minute run trains, the last 30% tests (10% gap). This asks whether the condition of a machine already seen can be recognised later in time. Because each fault comes from a single recording, part of a high time-split score may come from recognising the recording rather than the fault.

## 2. Camera: infrared images with a pretrained CNN
`export-images` saves 150 infrared frames per run as `Images/excavator/<class>/excavator_<class>_<speed>_fNNN.png`. A pretrained ResNet18 is fine-tuned with data augmentation; the number of training rounds is chosen on validation runs. Retraining takes several minutes, so it is off by default.

In [3]:
TRAIN_CNN = False
if TRAIN_CNN and all(LOCAL.values()):
    run_script("Models/excavator.py", "export-images", tail=1)
    run_script("Models/excavator.py", "cnn-pretrained", tail=1)
    run_script("Models/excavator.py", "cnn-pretrained", "--split", "time", tail=1)
    run_script("Models/excavator.py", "cnn", tail=1)
rows = {}
for name, label in (("excavator_cnn_pretrained_4class.json", "MAIN (unseen speed) | Camera: pretrained ResNet18"),
                    ("excavator_cnn_4class.json", "MAIN (unseen speed) | Camera: small CNN"),
                    ("excavator_cnn_pretrained_4class_timesplit.json", "TIME SPLIT | Camera: pretrained ResNet18")):
    r = load(name)
    if r:
        rows[f"{label} (per run)"] = r["recording_level"]
show(rows)

,accuracy,balanced_accuracy,macro_precision,macro_recall,macro_f1
MAIN (unseen speed) | Camera: pretrained ResNet18 (per run),0.312,0.312,0.220,0.312,0.254
MAIN (unseen speed) | Camera: small CNN (per run),0.312,0.312,0.271,0.312,0.267
TIME SPLIT | Camera: pretrained ResNet18 (per run),0.938,0.938,0.950,0.938,0.936

![Pretrained CNN](../Figures/excavator/excavator_cnn_pretrained_4class.png) ![Time split](../Figures/excavator/excavator_cnn_pretrained_4class_timesplit.png)

**Data (CC BY 4.0):** CORA v2.1, DOI 10.34810/DATA2500 (downloaded in a browser because the repository shows a bot check; every file checked against the publisher MD5 by `python Models/excavator.py intake`).

## Try your own CSV
Put the path of any CSV in `CSV_FILE` and run this cell. It can be a **feature table** (same columns as `Processed_Data/excavator_sensor_features_4class.csv`, optional `class` column) or a **raw recording** (one column of sensor values). Set `LABEL` to the true class to see the accuracy. Classes: healthy, bearing, unbalance, misalignment. The saved model is trained on all project data, so testing on one of the project's own recordings gives an optimistic score; to test fairly, first run `python Models/excavator.py train-final --exclude <recording>`.

In [4]:
CSV_FILE = None   # e.g. r"C:/Users/me/Downloads/my_recording.csv"
LABEL = None      # true class if known
SPEED = None      # raw recordings only: "F5", "F15", "F50" or "F60"
if CSV_FILE:
    run_script("Models/excavator.py", "predict", "--csv", CSV_FILE, *((["--label", LABEL] if LABEL else []) + (["--speed", SPEED] if SPEED else [])), tail=25)
else:
    print("Set CSV_FILE to a CSV path to get predictions (and accuracy if LABEL is set).")

Set CSV_FILE to a CSV path to get predictions (and accuracy if LABEL is set).