# Wheel Loader (machine 6): electric drive motor — sensor vs camera

| | Sensor | Camera |
|---|---|---|
| Data | CORA vibration (Vx, 3 kHz) | CORA infrared camera |
| Classes | healthy, bearing defect, half-broken rotor bar, broken rotor bar | same four |
| Tested on | 16 runs, one speed held out at a time | the same 16 runs |
| Code | `Models/wheel_loader.py csv` | `Models/wheel_loader.py cnn-pretrained` |

Same CORA laboratory motor/gearbox rig, but **new fault data**: the two rotor-bar faults are CORA conditions no other machine in this project uses (healthy and bearing-defect runs are shared with the Excavator). Large wheel loaders can use electric drive, so the induction motor stands in for the loader's drive motor. Preprocessing uses training data only. Lab data, not a wheel loader; it classifies the present condition, not when to repair.

All of this machine's experiment code is in its `Models/` file; shared notebook set-up is in `notebook_helpers.py`. Run the cells from top to bottom with the **Capstone (.venv)** kernel.

In [1]:
from notebook_helpers import *

LOCAL = setup([
    ("Sensor: CORA vibration (Vx)", "Raw_Data/cora_vibration", "*_Vx.csv", 16),
    ("Camera: CORA infrared, faults", "Raw_Data/cora_drive_faults", "*.mat", 12),
    ("Camera: CORA infrared, healthy", "Raw_Data/cora_gear_wear", "H_*.mat", 4),
])

                 environment
git commit           b0e5ad2
python                3.11.9
kernel         project .venv
numpy                  2.4.6
scipy                 1.17.1
pandas                 2.3.3
scikit-learn           1.9.1
opencv-python      4.14.0.94
matplotlib            3.11.2

,location,files,MB,local
data,,,,
Sensor: CORA vibration (Vx),Raw_Data/cora_vibration,36/16,3956.3,True
"Camera: CORA infrared, faults",Raw_Data/cora_drive_faults,20/12,451.3,True
"Camera: CORA infrared, healthy",Raw_Data/cora_gear_wear,4/4,118.2,True

All data is local: running fully offline.

## 1. Sensor: vibration (CSV)
Each run's vibration becomes 1-second windows measured in **shaft orders** (multiples of the shaft speed): bearing defects show at higher orders and spikes; broken rotor bars change the motor's slip and the sidebands around the running speed. The features go into a CSV table; the model and feature set are chosen on validation speeds inside the training data, then tested once on the held-out speed.

In [2]:
if all(LOCAL.values()):
    run_script("Models/wheel_loader.py", "csv", tail=2)                    # main: unseen speed
    run_script("Models/wheel_loader.py", "csv", "--split", "time", tail=1)  # secondary: time split
csv_result, time_result = load("wheel_loader_csv_4class.json"), load("wheel_loader_csv_4class_timesplit.json")
show({"MAIN (unseen speed) | Sensor: validation-selected": csv_result["validation_selected"]["score"],
      **{f"MAIN (unseen speed) | Sensor: {k}": v for k, v in csv_result["models"].items()},
      **{f"TIME SPLIT | Sensor: {k}": v for k, v in time_result["models"].items()}})

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
C:\Users\laksh\Downloads\GitHub\capstone-week4\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

[Models/wheel_loader.py csv]
  Validation-selected model: accuracy 0.312  macro F1 0.325  (choices: ['vibration / Extra trees', 'vibration / Extra trees', 'vibration / Extra trees', 'vibration / Logistic regression'])
  Saved Processed_Data\wheel_loader_sensor_features_4class.csv, Results\wheel_loader\wheel_loader_csv_4class.json and Figures\wheel_loader\wheel_loader_csv_4class.png

[Models/wheel_loader.py csv --split time]
  Saved Results\wheel_loader\wheel_loader_csv_4class_timesplit.json and Figures\wheel_loader\wheel_loader_csv_4class_timesplit.png

,accuracy,balanced_accuracy,macro_precision,macro_recall,macro_f1
MAIN (unseen speed) | Sensor: validation-selected,0.312,0.312,0.350,0.312,0.325
MAIN (unseen speed) | Sensor: Majority class (control),0.250,0.250,0.062,0.250,0.100
MAIN (unseen speed) | Sensor: Logistic regression,0.312,0.312,0.458,0.312,0.317
MAIN (unseen speed) | Sensor: Random forest,0.250,0.250,0.134,0.250,0.174
TIME SPLIT | Sensor: Majority class (control),0.250,0.250,0.062,0.250,0.100
TIME SPLIT | Sensor: Logistic regression,0.750,0.750,0.792,0.750,0.757
TIME SPLIT | Sensor: Random forest,0.938,0.938,0.950,0.938,0.936

![CSV sensor model](../Figures/wheel_loader/wheel_loader_csv_4class.png) ![Time split](../Figures/wheel_loader/wheel_loader_csv_4class_timesplit.png)

**Two tests, clearly separated.** *Main (unseen speed):* each whole speed is held out, so the model must recognise a fault at a speed it never trained on; CORA has only one run per fault per speed, and every model stays near chance. *Time split (secondary, easier):* the first 60% of every 50-minute run trains, the last 30% tests (10% gap). This asks whether the condition of a machine already seen can be recognised later in time. Because each fault comes from a single recording, part of a high time-split score may come from recognising the recording rather than the fault.

## 2. Camera: infrared images with a pretrained CNN
`export-images` saves 150 infrared frames per run as `Images/wheel_loader/<class>/wheel_loader_<class>_<speed>_fNNN.png`. A pretrained ResNet18 is fine-tuned with data augmentation; the number of training rounds is chosen on validation runs. Retraining takes several minutes, so it is off by default.

In [3]:
TRAIN_CNN = False
if TRAIN_CNN and all(LOCAL.values()):
    run_script("Models/wheel_loader.py", "export-images", tail=1)
    run_script("Models/wheel_loader.py", "cnn-pretrained", tail=1)
    run_script("Models/wheel_loader.py", "cnn-pretrained", "--split", "time", tail=1)
rows = {}
for name, label in (("wheel_loader_cnn_pretrained_4class.json", "MAIN (unseen speed) | Camera: pretrained ResNet18"),
                    ("wheel_loader_cnn_pretrained_4class_timesplit.json", "TIME SPLIT | Camera: pretrained ResNet18")):
    r = load(name)
    if r:
        rows[f"{label} (per run)"] = r["recording_level"]
show(rows)

,accuracy,balanced_accuracy,macro_precision,macro_recall,macro_f1
MAIN (unseen speed) | Camera: pretrained ResNet18 (per run),0.312,0.312,0.308,0.312,0.304
TIME SPLIT | Camera: pretrained ResNet18 (per run),0.812,0.812,0.833,0.812,0.807

![Pretrained CNN](../Figures/wheel_loader/wheel_loader_cnn_pretrained_4class.png) ![Time split](../Figures/wheel_loader/wheel_loader_cnn_pretrained_4class_timesplit.png)

**Data (CC BY 4.0):** CORA v2.1, DOI 10.34810/DATA2500 (downloaded in a browser because the repository shows a bot check; every file checked against the publisher MD5 by `python Models/wheel_loader.py intake`).

## Proposal Week 6: advanced ensemble models (XGBoost / LightGBM)
The same CSV sensor features and the same held-out recordings, now with **XGBoost** and **LightGBM** next to random forest, extra trees and scikit-learn gradient boosting. Settings are fixed in advance; nothing is tuned on the test. `train_seconds` is the total training time.

In [4]:
if all(LOCAL.values()):
    run_script("Models/wheel_loader.py", "ensembles", tail=1)
    run_script("Models/wheel_loader.py", "ensembles", "--split", "time", tail=1)
show_ensembles("wheel_loader")

[Models/wheel_loader.py ensembles]
  Saved Results\wheel_loader\wheel_loader_ensembles.json and Figures\wheel_loader\wheel_loader_ensembles.png

[Models/wheel_loader.py ensembles --split time]
  Saved Results\wheel_loader\wheel_loader_ensembles_timesplit.json and Figures\wheel_loader\wheel_loader_ensembles_timesplit.png

,accuracy,balanced_accuracy,macro_f1,train_seconds
MAIN | Majority class (control),0.250,0.250,0.100,0.00
MAIN | Random forest,0.250,0.250,0.174,2.37
MAIN | Extra trees,0.250,0.250,0.230,1.40
MAIN | Gradient boosting (scikit-learn),0.250,0.250,0.222,8.69
MAIN | XGBoost,0.250,0.250,0.217,1.85
MAIN | LightGBM,0.250,0.250,0.210,1.66
TIME SPLIT (secondary) | Majority class (control),0.250,0.250,0.100,0.00
TIME SPLIT (secondary) | Random forest,0.938,0.938,0.936,0.74
TIME SPLIT (secondary) | Extra trees,0.938,0.938,0.936,0.45
TIME SPLIT (secondary) | Gradient boosting (scikit-learn),0.938,0.938,0.936,2.49
TIME SPLIT (secondary) | XGBoost,0.875,0.875,0.879,0.46
TIME SPLIT (secondary) | LightGBM,0.938,0.938,0.936,0.34

![Ensemble comparison](../Figures/wheel_loader/wheel_loader_ensembles.png)

## Week 7: anomaly detection (trained on healthy data only)
Isolation Forest and One-Class SVM learn only what **healthy** looks like; anything unusual raises an alarm. No fault labels are used for training. The alarm threshold is set from the healthy training recordings before testing. **ROC-AUC** (1.0 = perfect, 0.5 = guessing) shows how well the score separates healthy from faulty; **fault detection rate** and **false alarm rate** are at that fixed threshold.

In [5]:
if all(LOCAL.values()):
    run_script("Models/wheel_loader.py", "anomaly", tail=1)
    run_script("Models/wheel_loader.py", "anomaly", "--split", "time", tail=1)
show_anomaly("wheel_loader")

[Models/wheel_loader.py anomaly]
  Saved Results\wheel_loader\wheel_loader_anomaly.json and Figures\wheel_loader\wheel_loader_anomaly.png

[Models/wheel_loader.py anomaly --split time]
  Saved Results\wheel_loader\wheel_loader_anomaly_timesplit.json and Figures\wheel_loader\wheel_loader_anomaly_timesplit.png

,roc_auc,fault_detection_rate,false_alarm_rate,accuracy,test_recordings
MAIN | Isolation Forest,0.3958,0.0000,0.00,0.250,16.0
MAIN | One-Class SVM,0.5000,0.2500,0.25,0.375,16.0
TIME SPLIT (secondary) | Isolation Forest,0.8958,0.0000,0.00,0.250,16.0
TIME SPLIT (secondary) | One-Class SVM,0.6875,0.1667,0.00,0.375,16.0

![Anomaly scores](../Figures/wheel_loader/wheel_loader_anomaly.png)

Each dot is one test recording; above the dashed line = alarm. Green = healthy, red = faulty.

## Try your own CSV
Put the path of any CSV in `CSV_FILE` and run this cell. It can be a **feature table** (same columns as `Processed_Data/wheel_loader_sensor_features_4class.csv`, optional `class` column) or a **raw recording** (one column of sensor values). Set `LABEL` to the true class to see the accuracy. Classes: healthy, bearing, half_broken_bar, broken_bar. The saved model is trained on all project data, so testing on one of the project's own recordings gives an optimistic score; to test fairly, first run `python Models/wheel_loader.py train-final --exclude <recording>`.

In [6]:
CSV_FILE = None   # e.g. r"C:/Users/me/Downloads/my_recording.csv"
LABEL = None      # true class if known
SPEED = None      # raw recordings only: "F5", "F15", "F50" or "F60"
if CSV_FILE:
    run_script("Models/wheel_loader.py", "predict", "--csv", CSV_FILE, *((["--label", LABEL] if LABEL else []) + (["--speed", SPEED] if SPEED else [])), tail=25)
else:
    print("Set CSV_FILE to a CSV path to get predictions (and accuracy if LABEL is set).")

Set CSV_FILE to a CSV path to get predictions (and accuracy if LABEL is set).